global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'ml_model'
    static_configs:
      - targets: ['host.docker.internal:8001']  # For Windows/macOS
      # For Linux, use: ['localhost:8001']
